#Conf file to load touch-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
<<<<<<< HEAD   (66f674 Merge "meta-qti-touch: change file location")
goodix_ts
=======
qts.ko
focaltech_fts.ko
synaptics_tcm_ts.ko
nt36xxx-i2c.ko
>>>>>>> CHANGE (99558c touch dlkm: support nt36xxx-i2c.ko and synaptics.ko for meta)
